#!/usr/bin/env ruby

require 'Time'

if ARGV[0].to_s.match(/-s/)
  cmd = `pmset -g log | grep "Using" | grep "$(date "+%Y-%m-%d")" | grep -w "Wake" > .stats`
  stats = File.read(".stats")
  screen_on_since = stats.scan(/\d{2}:\d{2}:\d{2}/).join("") # string 
  time_now = Time.now 
  time_obj = Time.parse(screen_on_since)
  delta_time = time_now.to_i - time_obj.to_i
  puts "#{delta_time} seconds"
else
  puts "Usage: ./screenOnTime <options>\nSee https://www.github.com/rehmanh/MacBook-Battery-Stats for more details."
end


=begin
year = Time.now.year
month = '%02d' % Time.now.month
day = '%02d' % Time.now.day
pmset -g log | grep "Using" | grep "$(date "+%Y-%m-%d")" | grep -w "Wake" > .stats
cmd = `touch .stats ; chmod u+x .stats ; pmset -g log | grep Using | tail -n 1 > .stats`
=end
